### ISSUE TITLE
[enhancement] Cute pink dark theme?

### ISSUE THREAD

**Issue by demonlol** [openmindculture/intellij-cute-pink-light-theme#58]
Could I expect a togglable white/dark theme for this project? I'm a fan of pink themes, but I can't stand the white... If you're unable to, I can. I figured I'd ask first, seeing this repo is still somewhat active. Thanks in advance!

**Comment by openmindculture** [comment]
Hi @demonlol 
thanks for your request!

Yes, feel free to add pull requests if you like!

I started this theme in my spare time and didn't even finish, as I have other priorities right now.

There are existing dark pink themes (at least I know one, [Pink as Heck ](https://plugins.jetbrains.com/plugin/13917-pink-as-heck), but a togglable dark/light would be very cool!

Maybe we only need to change the editor theme and/or base theme, but I see you seem to have an idea already.

If you make a pull request, I will take the time to review, test and hopefully release an upgraded theme to Jetbrains.

**Comment by demonlol** [comment]
@openmindculture
Hey, thanks for responding so quickly.

I've taken a look at _Pink As Heck_, but the dev(s) went a little too overboard with the pink. I like your attempt much better. 

I'll see what I can do.

**Comment by openmindculture** [comment]
@demonlol since my last release, there have been untested updates by dependabot.
If the latest code in main branch should fail to build, you might have to revert to [tag 0.2.3](https://github.com/openmindculture/intellij-cute-pink-light-theme/releases/tag/0.2.3)

**Comment by openmindculture** [comment]
Ideas and possible features:
- [ ] switch light / dark inside the same theme?
- [ ] not entirely dark, unlike _Pink As Hack_, but
  - [ ] maybe keep the same side bar, menu colours etc. and only change to a dark editor pane?
  - [ ] don't mess with the syntax schemes, but choose some existing dark editor base theme

**Comment by openmindculture** [comment]
The easiest quick solution might be a downstream project, forked from Cute Pink Light Theme, that only changes the parent editor scheme from "Default" (light) to a dark one and provides a distinct README description. Then we can merge any updates to the parent theme just by clicking a button in the GitHub UI.

**Comment by openmindculture** [comment]
https://github.com/openmindculture/intellij-cute-pink-dark-theme/pull/1 @demonlol Tyler if you want to have a look. Feedback, enhancements, collaborations are still very welcome.
